name = "RationalUnivariateRepresentation"
uuid = "17246082-4fa7-4287-87d4-6a5617fca855"
authors = ["Alexander Demin <asdemin_2@edu.hse.ru>", "Fabrice Rouillier <Fabrice.Rouillier@inria.fr>", "Joao Ruiz <joao.ruiz@imj-prg.fr>"]
version = "0.0.1"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Groebner = "0b43b601-686d-58a3-8a1c-6623616c7cd4"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"

[compat]
AbstractAlgebra = "0.36"
Groebner = "0.7.0"
Nemo = "0.40"
PrecompileTools = "1"
Primes = "0.5"
julia = "1.6"
