image: registry.gitlab.inria.fr/navarop/julia:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - ci.inria.fr
    - large
  script:
    - julia -e 'using Pkg; println(pwd()); println(readdir()); Pkg.activate(; temp=true); Pkg.develop(path="Julia/RationalUnivariateRepresentation.jl"); Pkg.status(); Pkg.build("RationalUnivariateRepresentation");'

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags:
    - ci.inria.fr
    - large
  script:
    - julia -e 'using Pkg; Pkg.activate(; temp=true); Pkg.develop(path="Julia/RationalUnivariateRepresentation.jl"); Pkg.build("RationalUnivariateRepresentation"); Pkg.status(); Pkg.test("RationalUnivariateRepresentation"; coverage = true)'  # adapted from https://gitlab.com/gitlab-examples/julia/-/blob/master/.gitlab-ci.yml
    # Comment out below if you do not want coverage results.
    - julia -e 'using Pkg; Pkg.add("Coverage"); 
      import RationalUnivariateRepresentation; cd(joinpath(dirname(pathof(RationalUnivariateRepresentation)), ".."));
      using Coverage; cl, tl = get_summary(process_folder());
      println("(", cl/tl*100, "%) covered")'

